In [23]:
import requests
import lxml.html as lh
import pandas as pd

In [63]:
url='https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
page =requests.get(url)
doc= lh.fromstring(page.content)
x_headers= doc.xpath('//tr')

In [64]:
[len(T) for T in x_headers[:12]]

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

In [65]:
x_headers=doc.xpath('//tr')
col=[]
i=0

for t in x_headers[0]:
    i+=1
    name=t.text_content()
    print ('%d:"%s"'%(i,name))
    col.append((name,[]))

1:"Postal Code
"
2:"Borough
"
3:"Neighbourhood
"

In [66]:
for j in range(1,len(tr_elements)):
    #T is our j'th row
    T=tr_elements[j]
    
    #If row is not of size 3, the //tr data is not from our table 
    if len(T)!=3:
        break
    
    #i is the index of our column
    i=0
    
    #Iterate through each element of the row
    for t in T.iterchildren():
        data=t.text_content() 
        #Check if row is empty
        if i>0:
        #Convert any numerical value to integers
            try:
                data=int(data)
            except:
                pass
        #Append the data to the empty list of the i'th column
        col[i][1].append(data)
        #Increment i for the next column
        i+=1

In [67]:
[len(C) for (title,C) in col]

[181, 181, 181]

In [68]:
Dict={title:column for (title,column) in col}
df=pd.DataFrame(Dict)

In [69]:
df.head(5)

  Postal Code\n           Borough\n              Neighbourhood\n
0         M1A\n      Not assigned\n               Not assigned\n
1         M2A\n      Not assigned\n               Not assigned\n
2         M3A\n        North York\n                  Parkwoods\n
3         M4A\n        North York\n           Victoria Village\n
4         M5A\n  Downtown Toronto\n  Regent Park, Harbourfront\n

In [70]:


df.columns = ['Borough', 'Neighbourhood','Postcode']

cols = df.columns.tolist()
cols

cols = cols[-1:] + cols[:-1]

cols = cols[-1:] + cols[:-1]

df = df[cols]

df.head()

        Neighbourhood                     Postcode Borough
0      Not assigned\n               Not assigned\n   M1A\n
1      Not assigned\n               Not assigned\n   M2A\n
2        North York\n                  Parkwoods\n   M3A\n
3        North York\n           Victoria Village\n   M4A\n
4  Downtown Toronto\n  Regent Park, Harbourfront\n   M5A\n

In [71]:
df = df.replace('\n',' ', regex=True)
df.head()

       Neighbourhood                    Postcode Borough
0      Not assigned                Not assigned     M1A
1      Not assigned                Not assigned     M2A
2        North York                   Parkwoods     M3A
3        North York            Victoria Village     M4A
4  Downtown Toronto   Regent Park, Harbourfront     M5A

In [72]:


df.drop(df.index[df['Borough'] == 'Not assigned'], inplace = True)

# Reset the index and dropping the previous index
df = df.reset_index(drop=True)

df.head(10)

       Neighbourhood                                      Postcode Borough
0      Not assigned                                  Not assigned     M1A
1      Not assigned                                  Not assigned     M2A
2        North York                                     Parkwoods     M3A
3        North York                              Victoria Village     M4A
4  Downtown Toronto                     Regent Park, Harbourfront     M5A
5        North York              Lawrence Manor, Lawrence Heights     M6A
6  Downtown Toronto   Queen's Park, Ontario Provincial Government     M7A
7      Not assigned                                  Not assigned     M8A
8         Etobicoke       Islington Avenue, Humber Valley Village     M9A
9       Scarborough                                Malvern, Rouge     M1B

In [75]:
df = df.groupby(['Postcode', 'Borough'])['Neighbourhood'].apply(','.join).reset_index()
df.columns = ['Postcode','Borough','Neighbourhood']
df.head(10)

,Postcode,Borough,Neighbourhood
0,,,Canadian postal codes
1,Agincourt,M1S,Scarborough
2,"Alderwood, Long Branch",M8W,Etobicoke
3,"Bathurst Manor, Wilson Heights, Downsview North",M3H,North York
4,Bayview Village,M2K,North York
5,"Bedford Park, Lawrence Manor East",M5M,North York
6,Berczy Park,M5E,Downtown Toronto
7,"Birch Cliff, Cliffside West",M1N,Scarborough
8,"Brockton, Parkdale Village, Exhibition Place",M6K,West Toronto
9,"Business reply mail Processing Centre, South C...",M7Y,East Toronto

In [77]:


df['Neighbourhood'] = df['Neighbourhood'].str.strip()

In [78]:
df.loc[df['Neighbourhood'] == 'Not assigned', 'Neighbourhood'] = df['Borough']

In [84]:
# Check if the Neighbourhood for Queen's Park changed 
df[df['Borough'] == 'Queen\'s Park']

Empty DataFrame
Columns: [Postcode, Borough, Neighbourhood]
Index: []

In [85]:


# Check the shape of the data frame
df.shape

(181, 3)